### ISSUE TITLE
Disable ha-cluster-ip requirement check for k8s only

### ISSUE THREAD

**Issue by joshkelly** [platform9/pf9-express#111]
This was for a ./pf9-express -a k8s-worker install

TASK [pre-flight-checks : set_fact] ************************************************************************************************************************************************************************
fatal: [good-swift]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ha_cluster_ip' is undefined\n\nThe error appears to have been in '/home/ubuntu/pf9-express/roles/pre-flight-checks/tasks/main.yml': line 42, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- set_fact:\n ^ here\n"}

**Comment by mmccarre** [comment]
Fixed in pull request #116
